export type Populate<T, K extends keyof T, V> = Omit<T, K> & {
  [P in K]: V;
};

export enum EmitterEvent {
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_UPDATED = "ORDER_UPDATED",
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
  ORDER_BROADCASTED = "ORDER_BROADCASTED",
  DELIVERY_ACCEPTED = "DELIVERY_ACCEPTED",
  DELIVERY_REJECTED = "DELIVERY_REJECTED",
  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  D_B_LOCATION_UPDATED = "D_B_LOCATION_UPDATED",
  MESSAGE_SENT = "MESSAGE_SENT",
}
