enum PAYMENT_METHOD {
  COD = "COD",
  CARD = "CARD",
}

enum ORDER_STATUS {
  PENDING = "PENDING",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
}

enum PRODUCT_UNIT {
  KG = "KG",
  GRAM = "GRAM",
  LITRE = "LITRE",
  ML = "ML",
  PIECE = "PIECE",
  PACK = "PACK",
  DOZEN = "DOZEN",
  BUNDLE = "BUNDLE",
  BAG = "BAG",
  BOX = "BOX",
  CAN = "CAN",
  BOTTLE = "BOTTLE",
  JAR = "JAR",
  TUBE = "TUBE",
  TRAY = "TRAY",
  PACKET = "PACKET",
  SACHET = "SACHET",
  ROLL = "ROLL",
  BAR = "BAR",
  GALLON = "GALLON",
  QUART = "QUART",
  SERVING = "SERVING",
  LB = "LB",
  OZ = "OZ",
}

enum PRODUCT_CATEGORY {
  VEGETABLES = "VEGETABLES",
  FRUITS = "FRUITS",
  DAIRY_EGGS = "DAIRY_EGGS",
  GRAINS = "GRAINS",
  SEAFOOD = "SEAFOOD",
  SPICES = "SPICES",
  BEVERAGES = "BEVERAGES",
  PERSONAL_CARE = "PERSONAL_CARE",
  HOUSEHOLD_ESSENTIALS = "HOUSEHOLD_ESSENTIALS",
  PACKAGED_FOOD = "PACKAGED_FOOD",
  BABY_CARE = "BABY_CARE",
  PET_CARE = "PET_CARE",
  HEALTH_AND_WELLNESS = "HEALTH_AND_WELLNESS",
  CANNED_GOODS = "CANNED_GOODS",
  CONDIMENTS = "CONDIMENTS",
  FROZEN = "FROZEN",
  OTHERS = "OTHERS",
}

enum USER_ROLE {
  USER = "USER",
  DELIVERY_BOY = "DELIVERY_BOY",
  ADMIN = "ADMIN",
}

export {
  PAYMENT_METHOD,
  ORDER_STATUS,
  PRODUCT_UNIT,
  PRODUCT_CATEGORY,
  USER_ROLE,
};
